/*
 * CadastraCliente.java
 *
 * Created on 06/06/2010, 23:05:21
 */

package imobiliaria.gui;


import imobiliaria.auxiliar.*;
import imobiliaria.controladores.*;
import imobiliaria.entidades.*;
import imobiliaria.util.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level; // Apagar
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 

/**
 * Gui para Cadastramento de clientes
 * @author Thiago Ferreira
 */
public class CadastraCliente extends javax.swing.JFrame {
    private Sistema sis;
    /** Creates new form CadastraCliente */
    public CadastraCliente() {
        sis = new Sistema();
        initComponents();
        setLocationRelativeTo(null);

        for (String ano : datasNascimentoValidas())
            JCB_Ano.addItem(ano);
        
        try {
            sis.atualizaDados();
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupPreferencia = new javax.swing.ButtonGroup();
        JL_Endereco = new javax.swing.JLabel();
        JL_Cpf = new javax.swing.JLabel();
        JL_Data = new javax.swing.JLabel();
        JTF_Nome = new javax.swing.JTextField();
        JTF_Cpf1 = new javax.swing.JTextField();
        JTF_Endereco = new javax.swing.JTextField();
        JP_Preferencia = new javax.swing.JPanel();
        rdbCasa = new javax.swing.JRadioButton();
        rdbApart = new javax.swing.JRadioButton();
        rdbTerreno = new javax.swing.JRadioButton();
        JL_TituloCC = new javax.swing.JLabel();
        JL_Info = new javax.swing.JLabel();
        JB_Cadastrar = new javax.swing.JButton();
        JB_Voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JL_Barra2 = new javax.swing.JLabel();
        JCB_Dia = new javax.swing.JComboBox();
        JL_Barra1 = new javax.swing.JLabel();
        JCB_Mes = new javax.swing.JComboBox();
        JCB_Ano = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("iMobiliaria - Cadastramento de Cliente");
        setResizable(false);

        JL_Endereco.setText("Endereço:");

        JL_Cpf.setText("CPF:");

        JL_Data.setText("Nascimento:");

        JTF_Nome.setToolTipText("Digite aqui seu nome");

        JTF_Cpf1.setToolTipText("Digite seu cpf");

        JTF_Endereco.setToolTipText("Digite seu endereço");

        JP_Preferencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preferencia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bGroupPreferencia.add(rdbCasa);
        rdbCasa.setSelected(true);
        rdbCasa.setText("Casa");

        bGroupPreferencia.add(rdbApart);
        rdbApart.setText("Apartamento");

        bGroupPreferencia.add(rdbTerreno);
        rdbTerreno.setText("Terreno");

        javax.swing.GroupLayout JP_PreferenciaLayout = new javax.swing.GroupLayout(JP_Preferencia);
        JP_Preferencia.setLayout(JP_PreferenciaLayout);
        JP_PreferenciaLayout.setHorizontalGroup(
            JP_PreferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_PreferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbCasa)
                .addGap(38, 38, 38)
                .addComponent(rdbApart)
                .addGap(18, 18, 18)
                .addComponent(rdbTerreno)
                .addContainerGap())
        );
        JP_PreferenciaLayout.setVerticalGroup(
            JP_PreferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_PreferenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JP_PreferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCasa)
                    .addComponent(rdbApart)
                    .addComponent(rdbTerreno))
                .addContainerGap())
        );

        setLocationRelativeTo(null);
        JL_TituloCC.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        JL_TituloCC.setText("Cadastramento de Cliente");

        JL_Info.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        JL_Info.setText("Preencha os dados abaixo, para se cadastrar:");

        JB_Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/okIcon.png"))); // NOI18N
        JB_Cadastrar.setText("Cadastrar-se");
        JB_Cadastrar.setToolTipText("Clique aqui para se cadastrar");
        JB_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CadastrarActionPerformed(evt);
            }
        });

        JB_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/backIcon.png"))); // NOI18N
        JB_Voltar.setText("Voltar");
        JB_Voltar.setToolTipText("Clique aqui para voltar à tela de login");
        JB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("( Digite apenas os números )");

        jLabel2.setText("Nome:");

        JL_Barra2.setText("/");

        JCB_Dia.setMaximumRowCount(5);
        JCB_Dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        JL_Barra1.setText("/");

        JCB_Mes.setMaximumRowCount(5);
        JCB_Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        JCB_Ano.setMaximumRowCount(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(JB_Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_Cadastrar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(JL_Info)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(JL_TituloCC, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Endereco)
                    .addComponent(JL_Data)
                    .addComponent(jLabel2)
                    .addComponent(JL_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JP_Preferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JTF_Endereco)
                        .addComponent(JTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_Barra1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_Barra2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCB_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTF_Cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JL_TituloCC)
                .addGap(43, 43, 43)
                .addComponent(JL_Info)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Endereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Barra1)
                    .addComponent(JCB_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_Barra2)
                    .addComponent(JL_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCB_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JL_Cpf))
                .addGap(29, 29, 29)
                .addComponent(JP_Preferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_Voltar)
                    .addComponent(JB_Cadastrar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JB_Cadastrar, JB_Voltar});

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-640)/2, (screenSize.height-480)/2, 640, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void JB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_JB_VoltarActionPerformed
 
    private void JB_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CadastrarActionPerformed
        boolean cadastroOK = false;
        String cpf = JTF_Cpf1.getText();
        String endereco = JTF_Endereco.getText();
        String nome = JTF_Nome.getText();

        TipoImovel preferencia = null;
        if(rdbApart.isSelected()){
            preferencia = TipoImovel.APARTAMENTO;
        } else if( rdbCasa.isSelected()){
            preferencia = TipoImovel.CASA;
        } else if ( rdbTerreno.isSelected()){
            preferencia = TipoImovel.TERRENO;
        }

        String diaStr = JCB_Dia.getSelectedItem().toString();
        int mes = MetodoEntrada.recebeMesPeloNome(JCB_Mes.getSelectedItem().toString());
        String anoStr = JCB_Ano.getSelectedItem().toString();

        int dia = Integer.parseInt(diaStr);
        int ano = Integer.parseInt(anoStr);
        Calendar dataNascimento = new GregorianCalendar(ano,mes,dia);

        try {
            ControladorCliente.getInstance().adicionaCliente(cpf, dataNascimento, endereco, nome, preferencia);
            Cliente novoCliente = ControladorCliente.getInstance().getCliente(
                    FormataEntrada.cpf(cpf));

            ControladorLogin.getInstance().adicionaLogin(novoCliente.getLogin());
            cadastroOK = true;
            sis.salvarDados();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Verifique se esses campos foram\n" +
                    "preenchidos corretamente:\n\n" +ex.getMessage(),
                    "Erro Ao Cadastrar", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(CadastraCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (cadastroOK){
          JOptionPane.showMessageDialog(null, CADASTROEFETUADO,
                    "Cadastro Efetuado", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_JB_CadastrarActionPerformed

    /*
     * Metodo que retorna um array que ira ser adicionado no JComboBox,
     * de datas de nascimentos validas para seremcselecionadas pelo usuario,
     */
    private static String[] datasNascimentoValidas(){
        Calendar hoje = new GregorianCalendar();
        int MAIORDEIDADE = 18;
        int IDADELIMITE = 90;
        int primeiroAnoValido = hoje.get(Calendar.YEAR) - MAIORDEIDADE;
        int ultimoAnoValido = primeiroAnoValido - IDADELIMITE;
        int qtosAnosMostrar = primeiroAnoValido - ultimoAnoValido;
        String[] anosValidos = new String[qtosAnosMostrar];
        
        for(int i=0; i < qtosAnosMostrar;i++){
            int anoAdicionado = primeiroAnoValido - i;
            anosValidos[i] = Integer.toString(anoAdicionado);
        }
        return anosValidos;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Cadastrar;
    private javax.swing.JButton JB_Voltar;
    private javax.swing.JComboBox JCB_Ano;
    private javax.swing.JComboBox JCB_Dia;
    private javax.swing.JComboBox JCB_Mes;
    private javax.swing.JLabel JL_Barra1;
    private javax.swing.JLabel JL_Barra2;
    private javax.swing.JLabel JL_Cpf;
    private javax.swing.JLabel JL_Data;
    private javax.swing.JLabel JL_Endereco;
    private javax.swing.JLabel JL_Info;
    private javax.swing.JLabel JL_TituloCC;
    private javax.swing.JPanel JP_Preferencia;
    private javax.swing.JTextField JTF_Cpf1;
    private javax.swing.JTextField JTF_Endereco;
    private javax.swing.JTextField JTF_Nome;
    private javax.swing.ButtonGroup bGroupPreferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbApart;
    private javax.swing.JRadioButton rdbCasa;
    private javax.swing.JRadioButton rdbTerreno;
    // End of variables declaration//GEN-END:variables
    // Atributos
    
    private final String CADASTROEFETUADO = "Seu cadastro foi efetuado" +
    " com sucesso!\n\nLembre-se:\n" +
    "Seu login é seu cpf:\n" +
    "   Neste formato: 12345678910\n" +
    "Sua senha é sua data de nascimento\n" +
    "   Neste formato: 01011991\n\n" +
    "Você pode mudar seu login/senha quando desejar";
    // Fim de declaracao de atributos
}