/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceFuncionario.java
 *
 * Created on 04/07/2010, 15:54:44
 */

package imobiliaria.gui;

/**
 *
 * @author Thiago Ferreira
 */
public class InterfaceFuncionario extends javax.swing.JFrame {

    /** Creates new form InterfaceFuncionario */
    public InterfaceFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Ola = new javax.swing.JLabel();
        JB_Cliente = new javax.swing.JButton();
        JB_Imovel = new javax.swing.JButton();
        JB_Aluguel = new javax.swing.JButton();
        JB_Pedido = new javax.swing.JButton();
        JB_VerDados = new javax.swing.JButton();
        JL_Logo = new javax.swing.JLabel();
        JB_Voltar = new javax.swing.JButton();
        JL_Option = new javax.swing.JLabel();
        JL_BoasVindas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opções Funcionario");
        setResizable(false);

        JL_Ola.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JL_Ola.setText("Olá,");

        JB_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/addIcon.png"))); // NOI18N
        JB_Cliente.setText("Clientes");
        JB_Cliente.setToolTipText("");
        JB_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_ClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_ClienteMouseEntered(evt);
            }
        });
        JB_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ClienteActionPerformed(evt);
            }
        });

        JB_Imovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/homeIcon.png"))); // NOI18N
        JB_Imovel.setText("Imóveis");
        JB_Imovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_ImovelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_ImovelMouseEntered(evt);
            }
        });
        JB_Imovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ImovelActionPerformed(evt);
            }
        });

        JB_Aluguel.setText("Aluguéis");
        JB_Aluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_AluguelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_AluguelMouseEntered(evt);
            }
        });
        JB_Aluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AluguelActionPerformed(evt);
            }
        });

        JB_Pedido.setText("Pedidos");
        JB_Pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_PedidoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_PedidoMouseEntered(evt);
            }
        });
        JB_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PedidoActionPerformed(evt);
            }
        });

        JB_VerDados.setText("Verifique seus dados");
        JB_VerDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_VerDadosMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_VerDadosMouseEntered(evt);
            }
        });

        JL_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/iMobLogo.png"))); // NOI18N

        JB_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/backIcon.png"))); // NOI18N
        JB_Voltar.setText("Voltar");
        JB_Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_VoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_VoltarMouseEntered(evt);
            }
        });
        JB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VoltarActionPerformed(evt);
            }
        });

        JL_Option.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        JL_Option.setText("Escolha uma das opções.");

        JL_BoasVindas.setText("Bem-vindo as opções de funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JB_Cliente))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JB_Imovel)
                        .addGap(115, 115, 115)
                        .addComponent(JL_Option))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JL_Ola)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(JL_BoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JB_VerDados))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(JB_Aluguel))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(JB_Pedido))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(JB_Voltar)))
                            .addGap(209, 209, 209)
                            .addComponent(JL_Logo))))
                .addGap(21, 21, 21))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JB_Aluguel, JB_Cliente, JB_Imovel, JB_Pedido});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_Ola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_BoasVindas))
                    .addComponent(JB_VerDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(JB_Cliente)
                        .addGap(30, 30, 30)
                        .addComponent(JB_Imovel)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_Option)
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_Aluguel)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Pedido))
                    .addComponent(JL_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addComponent(JB_Voltar)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JB_Aluguel, JB_Cliente, JB_Imovel, JB_Pedido});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ClienteActionPerformed
        new InterfaceOpClientes().setVisible(true);

    }//GEN-LAST:event_JB_ClienteActionPerformed

    private void JB_ImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ImovelActionPerformed
        // Opcoes de imovel
    }//GEN-LAST:event_JB_ImovelActionPerformed

    private void JB_AluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AluguelActionPerformed
        // Opcoes de aluguel
    }//GEN-LAST:event_JB_AluguelActionPerformed

    private void JB_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PedidoActionPerformed
        // Opcoes de pedido
    }//GEN-LAST:event_JB_PedidoActionPerformed

    private void JB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VoltarActionPerformed
        // Voltar a telaprincipal
    }//GEN-LAST:event_JB_VoltarActionPerformed

    private void JB_ClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ClienteMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para abrir as opções de cliente");
    }//GEN-LAST:event_JB_ClienteMouseEntered

    private void JB_ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ClienteMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_ClienteMouseExited

    private void JB_ImovelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ImovelMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para abrir as opções de imóvel");
    }//GEN-LAST:event_JB_ImovelMouseEntered

    private void JB_ImovelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ImovelMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_ImovelMouseExited

    private void JB_AluguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AluguelMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para abrir as opções de aluguel");
    }//GEN-LAST:event_JB_AluguelMouseEntered

    private void JB_AluguelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AluguelMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_AluguelMouseExited

    private void JB_PedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_PedidoMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para abrir as opções de pedidos");
    }//GEN-LAST:event_JB_PedidoMouseEntered

    private void JB_PedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_PedidoMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_PedidoMouseExited

    private void JB_VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VoltarMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para voltar a tela principal");
    }//GEN-LAST:event_JB_VoltarMouseEntered

    private void JB_VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VoltarMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_VoltarMouseExited

    private void JB_VerDadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VerDadosMouseEntered
       JL_Option.setForeground(new java.awt.Color(255, 0, 0));
       JL_Option.setText("Clique para verificar seus dados");
    }//GEN-LAST:event_JB_VerDadosMouseEntered

    private void JB_VerDadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VerDadosMouseExited
       JL_Option.setForeground(new java.awt.Color(0,0,0));
       JL_Option.setText(TEXTOCENTRAL);
    }//GEN-LAST:event_JB_VerDadosMouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Aluguel;
    private javax.swing.JButton JB_Cliente;
    private javax.swing.JButton JB_Imovel;
    private javax.swing.JButton JB_Pedido;
    private javax.swing.JButton JB_VerDados;
    private javax.swing.JButton JB_Voltar;
    private javax.swing.JLabel JL_BoasVindas;
    private javax.swing.JLabel JL_Logo;
    private javax.swing.JLabel JL_Ola;
    private javax.swing.JLabel JL_Option;
    // End of variables declaration//GEN-END:variables
    private String TEXTOCENTRAL = "Escolha uma das opções.";
}
