/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceDadosCliente.java
 *
 * Created on 04/07/2010, 21:05:16
 */

package imobiliaria.gui;

/**
 *
 * @author bruno
 */
public class InterfaceDadosCliente extends javax.swing.JFrame {

    /** Creates new form InterfaceDadosCliente */
    public InterfaceDadosCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JL_DadosDoCliente = new javax.swing.JLabel();
        JP_Painel = new javax.swing.JPanel();
        JL_Nome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JL_NomeDoCliente = new javax.swing.JLabel();
        JL_CPFDoCLiente = new javax.swing.JLabel();
        JL_EndereceDoCliente = new javax.swing.JLabel();
        JL_NascimentoDoCliente = new javax.swing.JLabel();
        JL_PreferenciaDoCliente = new javax.swing.JLabel();
        JB_Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_DadosDoCliente.setText("DADOS DO CLIENTE");

        JL_Nome.setText("Nome:");

        jLabel1.setText("CPF:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Nascimento:");

        jLabel4.setText("Preferencia:");

        JL_NomeDoCliente.setText("Bruno Fábio de Farias Paiva");

        JL_CPFDoCLiente.setText("XXX.XXX.XXX-XX");

        JL_EndereceDoCliente.setText("Rua Alberto de Brito, 844");

        JL_NascimentoDoCliente.setText("04 / 04 / 1991");

        JL_PreferenciaDoCliente.setText("CASA");

        javax.swing.GroupLayout JP_PainelLayout = new javax.swing.GroupLayout(JP_Painel);
        JP_Painel.setLayout(JP_PainelLayout);
        JP_PainelLayout.setHorizontalGroup(
            JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_PainelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_Nome)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_NomeDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_CPFDoCLiente)
                    .addComponent(JL_EndereceDoCliente)
                    .addComponent(JL_NascimentoDoCliente)
                    .addComponent(JL_PreferenciaDoCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_PainelLayout.setVerticalGroup(
            JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_PainelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_Nome)
                    .addComponent(JL_NomeDoCliente))
                .addGap(29, 29, 29)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JL_CPFDoCLiente))
                .addGap(26, 26, 26)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JL_EndereceDoCliente))
                .addGap(33, 33, 33)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JL_NascimentoDoCliente))
                .addGap(28, 28, 28)
                .addGroup(JP_PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JL_PreferenciaDoCliente))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        JB_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/backIcon.png"))); // NOI18N
        JB_Voltar.setText("Voltar");
        JB_Voltar.setToolTipText("Clique aqui para voltar à tela de login");
        JB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(JB_Voltar)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JP_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(JL_DadosDoCliente)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_DadosDoCliente)
                .addGap(18, 18, 18)
                .addComponent(JP_Painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(JB_Voltar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void JB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {
        new InterfaceCliente().setVisible(true);
        //AQUI Nao ERA PRA SER NEW, E SIM PRA TORNAR true A JANELA ANTERIORMENTE ABERTA
        dispose();
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDadosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton JB_Voltar;
    private javax.swing.JLabel JL_CPFDoCLiente;
    private javax.swing.JLabel JL_DadosDoCliente;
    private javax.swing.JLabel JL_EndereceDoCliente;
    private javax.swing.JLabel JL_NascimentoDoCliente;
    private javax.swing.JLabel JL_Nome;
    private javax.swing.JLabel JL_NomeDoCliente;
    private javax.swing.JLabel JL_PreferenciaDoCliente;
    private javax.swing.JPanel JP_Painel;
    private javax.swing.JPanel JP_Preferencia;
    private javax.swing.JPanel JP_Preferencia1;
    private javax.swing.JPanel JP_Preferencia2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rdbApart;
    private javax.swing.JRadioButton rdbApart1;
    private javax.swing.JRadioButton rdbApart2;
    private javax.swing.JRadioButton rdbCasa;
    private javax.swing.JRadioButton rdbCasa1;
    private javax.swing.JRadioButton rdbCasa2;
    private javax.swing.JRadioButton rdbTerreno;
    private javax.swing.JRadioButton rdbTerreno1;
    private javax.swing.JRadioButton rdbTerreno2;
    // End of variables declaration

}
