/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceAdmin.java
 *
 * Created on 04/07/2010, 15:15:06
 */

package imobiliaria.gui;

/**
 *
 * @author Convidado
 */
public class InterfaceAdmin extends javax.swing.JFrame {

    /** Creates new form InterfaceAdmin */
    public InterfaceAdmin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton16 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton20 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Ajuda = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu de Administração");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 210, 30);

        jLabel2.setText("Bem Vindo!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 70, 14);

        jLabel3.setText("Saldo Atual do Caixa: 00,00");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 530, 170, 14);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButton1.setText("Cadastro");
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 40, 130, 23);

        jButton2.setText("Modificar Dados");
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 70, 130, 23);

        jButton3.setText("Excluir");
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 130, 130, 23);

        jButton4.setText("Ver Informacoes");
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 100, 130, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Clientes");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 10, 67, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 70, 150, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setName("null"); // NOI18N
        jPanel2.setLayout(null);

        jButton6.setText("Excluir");
        jPanel2.add(jButton6);
        jButton6.setBounds(10, 130, 130, 23);

        jButton7.setText("Ver Informacoes");
        jPanel2.add(jButton7);
        jButton7.setBounds(10, 100, 130, 23);

        jButton5.setText("Cadastro");
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 40, 130, 23);

        jButton8.setText("Modificar Dados");
        jPanel2.add(jButton8);
        jButton8.setBounds(10, 70, 130, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Funcionarios");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 10, 100, 17);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(170, 70, 150, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/iMobLogo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 50, 250, 200);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Imoveis");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 10, 100, 17);

        jButton9.setText("Cadastro");
        jPanel3.add(jButton9);
        jButton9.setBounds(10, 40, 130, 23);

        jButton11.setText("Ver Informacoes");
        jPanel3.add(jButton11);
        jButton11.setBounds(10, 100, 130, 23);

        jButton12.setText("Excluir");
        jPanel3.add(jButton12);
        jButton12.setBounds(10, 130, 130, 23);

        jButton10.setText("Modificar Dados");
        jPanel3.add(jButton10);
        jButton10.setBounds(10, 70, 130, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 70, 150, 170);

        jLabel8.setText("Efetuar Pedidos: (Quick Accept)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 270, 200, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "InfoPedido1", "InfoPedido2", "InfoPedido3" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(500, 290, 260, 22);

        jButton13.setText("Efetuar");
        getContentPane().add(jButton13);
        jButton13.setBounds(500, 320, 81, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Financeiro");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 10, 90, 17);

        jLabel12.setText("Data do Ultimo Pagamento Efetuado: XX/XX/XXXX");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 30, 280, 14);

        jLabel13.setText("Pagamento já efetuado no mes");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(300, 10, 160, 14);

        jToggleButton1.setText("Efetua Pagamento");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton1);
        jToggleButton1.setBounds(250, 90, 190, 23);

        jButton16.setText("Ver Folha de Pagamento");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton16);
        jButton16.setBounds(30, 90, 190, 23);

        jToggleButton2.setText("Listar Transacoes Mensais");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton2);
        jToggleButton2.setBounds(30, 60, 190, 23);

        jToggleButton3.setText("Listar Transacoes");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton3);
        jToggleButton3.setBounds(250, 60, 190, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 250, 470, 130);

        jButton14.setText("Excluir");
        getContentPane().add(jButton14);
        jButton14.setBounds(680, 320, 80, 23);

        jButton15.setText("Ver Info");
        getContentPane().add(jButton15);
        jButton15.setBounds(590, 320, 81, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Logins do Sistema");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 10, 150, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Login1", "Login2", "Login3", "Login4" }));
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(10, 70, 230, 22);

        jButton20.setText("Verificar Login");
        jPanel5.add(jButton20);
        jButton20.setBounds(10, 110, 110, 23);

        jLabel14.setText("Numero Total de Logins: XX");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 40, 220, 14);

        jButton21.setText("Modificar Login");
        jPanel5.add(jButton21);
        jButton21.setBounds(130, 110, 110, 23);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(500, 360, 260, 160);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Alugueis e Pedidos");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(10, 10, 140, 17);

        jToggleButton4.setText("Listar Alugueis");
        jPanel6.add(jToggleButton4);
        jToggleButton4.setBounds(40, 40, 170, 23);

        jButton17.setText("BOTAOSEMFUNCAO");
        jPanel6.add(jButton17);
        jButton17.setBounds(40, 80, 170, 23);

        jButton18.setText("Listar Pedidos");
        jPanel6.add(jButton18);
        jButton18.setBounds(260, 40, 170, 23);

        jButton19.setText("BOTAOSEMFUNCAO");
        jPanel6.add(jButton19);
        jButton19.setBounds(260, 80, 170, 23);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 390, 470, 130);

        jMenu1.setText("Principal");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        Ajuda.add(jMenu1);

        jMenu2.setText("Cliente");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        Ajuda.add(jMenu2);

        jMenu3.setText("Funcionario");

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        Ajuda.add(jMenu3);

        jMenu4.setText("Imoveis");

        jMenuItem4.setText("jMenuItem4");
        jMenu4.add(jMenuItem4);

        Ajuda.add(jMenu4);

        jMenu5.setText("Pagamentos");

        jMenuItem5.setText("jMenuItem5");
        jMenu5.add(jMenuItem5);

        Ajuda.add(jMenu5);

        jMenu6.setText("Ajuda");

        jMenuItem6.setText("jMenuItem6");
        jMenu6.add(jMenuItem6);

        Ajuda.add(jMenu6);

        setJMenuBar(Ajuda);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Ajuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables

}
