/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceCliente.java
 *
 * Created on 04/07/2010, 14:30:19
 */

package imobiliaria.gui;

/**
 * @author bruno
 */
public class InterfaceCliente extends javax.swing.JFrame {

    /** Creates new form InterfaceCliente */
    public InterfaceCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JL_Cliente = new javax.swing.JLabel();
        JL_NomeDeCliente = new javax.swing.JLabel();
        JB_VerificaPedidos = new javax.swing.JButton();
        JB_VerificaAlugueis = new javax.swing.JButton();
        JB_VerificaHistoricoCompras = new javax.swing.JButton();
        JB_Desloga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_ImoveisCliente = new javax.swing.JList();
        JB_VerificaDadosCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JL_Cliente.setText("CLIENTE");

        JL_NomeDeCliente.setText("- Nome Do Cliente Que Se Logou Ficará Aqui Entre Os Hífens -");

        JB_VerificaPedidos.setText("Verificar Pedidos");
        JB_VerificaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VerificaPedidosActionPerformed(evt);
            }
        });

        JB_VerificaAlugueis.setText("Verificar Alugueis");

        JB_VerificaHistoricoCompras.setText("Ver Histórico De Compras");

        JB_Desloga.setIcon(new javax.swing.ImageIcon("/home/bruno/workspacelcc3/iMobiliaria/src/imobiliaria/images/exitIcon.png")); // NOI18N
        JB_Desloga.setText("Deslogar");

        JL_ImoveisCliente.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_ImoveisCliente);

        JB_VerificaDadosCliente.setText("Verificar Seus Dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(JL_Cliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JB_VerificaDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(JB_Desloga, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JB_VerificaHistoricoCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JB_VerificaAlugueis, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JB_VerificaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(JL_NomeDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JL_Cliente)
                .addGap(18, 18, 18)
                .addComponent(JL_NomeDeCliente)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_VerificaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_VerificaAlugueis, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_VerificaHistoricoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_VerificaDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(JB_Desloga, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>

    private void JB_VerificaPedidosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton JB_Desloga;
    private javax.swing.JButton JB_VerificaAlugueis;
    private javax.swing.JButton JB_VerificaDadosCliente;
    private javax.swing.JButton JB_VerificaHistoricoCompras;
    private javax.swing.JButton JB_VerificaPedidos;
    private javax.swing.JLabel JL_Cliente;
    private javax.swing.JList JL_ImoveisCliente;
    private javax.swing.JLabel JL_NomeDeCliente;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration

    //JL_NomeDeCliente = Cliente.getNome();
    
}
