/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceAdmin.java
 *
 * Created on 04/07/2010, 15:15:06
 */

package imobiliaria.gui;

import imobiliaria.controladores.ControladorAlugueis;
import imobiliaria.controladores.ControladorLogin;
import imobiliaria.controladores.ControladorPedidos;
import imobiliaria.controladores.ControladorTransacoes;
import imobiliaria.entidades.FolhaDePagamento;
import imobiliaria.entidades.Sistema;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Convidado
 */
public class InterfaceAdmin extends javax.swing.JFrame {

    private Sistema sis = new Sistema();

    /** Creates new form InterfaceAdmin */
    public InterfaceAdmin() {

        try {
        sis.atualizaDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:\n" + e.getMessage(),
                    "Erro ao Atualizar Dados", JOptionPane.ERROR_MESSAGE);

        }

        initComponents();

        setLocationRelativeTo(null);

        atualizaInterface();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JL_SaldoAtualCaixa = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JL_DataUltimoPagamento = new javax.swing.JLabel();
        JB_VerFolhaDePagamento = new javax.swing.JButton();
        JL_Pagamento = new javax.swing.JLabel();
        JB_ListaTransacoes = new javax.swing.JButton();
        JB_ListaTransacoesMensais = new javax.swing.JButton();
        JB_EfetuaPagamento = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JCB_Logins = new javax.swing.JComboBox();
        JB_VerInfoLogin = new javax.swing.JButton();
        JL_NumTotalLogins = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JB_ListaPedidos = new javax.swing.JButton();
        JCB_Alugueis = new javax.swing.JComboBox();
        JB_CancelarAluguel = new javax.swing.JButton();
        JB_VerInfoAluguel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JB_ExcluirPedido = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        JB_VerInfoPedido = new javax.swing.JButton();
        JB_EfetuarPedido = new javax.swing.JButton();
        JCB_Pedidos = new javax.swing.JComboBox();
        JB_ListaAlugueis = new javax.swing.JButton();
        JB_MenuImoveis = new javax.swing.JButton();
        JB_MenuClientes = new javax.swing.JButton();
        JB_MenuFuncionarios = new javax.swing.JButton();
        JL_NumTotalPedidos = new javax.swing.JLabel();
        JL_NumTotalAlugueis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Menu de Administração");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 210, 30);

        jLabel2.setText("Bem Vindo!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 70, 14);

        JL_SaldoAtualCaixa.setText("Saldo Atual do Caixa: 00,00");
        getContentPane().add(JL_SaldoAtualCaixa);
        JL_SaldoAtualCaixa.setBounds(10, 530, 170, 14);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/iMobLogo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 100, 250, 200);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel11.setText("Financeiro");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 10, 90, 17);

        JL_DataUltimoPagamento.setText("Data do Ultimo Pagamento Efetuado: XX/XX/XXXX");
        jPanel4.add(JL_DataUltimoPagamento);
        JL_DataUltimoPagamento.setBounds(10, 30, 450, 14);

        JB_VerFolhaDePagamento.setText("Ver Folha de Pagamento");
        JB_VerFolhaDePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VerFolhaDePagamentoActionPerformed(evt);
            }
        });
        jPanel4.add(JB_VerFolhaDePagamento);
        JB_VerFolhaDePagamento.setBounds(30, 90, 190, 23);
        jPanel4.add(JL_Pagamento);
        JL_Pagamento.setBounds(420, 10, 40, 30);

        JB_ListaTransacoes.setText("Lista Transacoes");
        JB_ListaTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListaTransacoesActionPerformed(evt);
            }
        });
        jPanel4.add(JB_ListaTransacoes);
        JB_ListaTransacoes.setBounds(250, 60, 190, 23);

        JB_ListaTransacoesMensais.setText("Lista Transacoes Mensais");
        JB_ListaTransacoesMensais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListaTransacoesMensaisActionPerformed(evt);
            }
        });
        jPanel4.add(JB_ListaTransacoesMensais);
        JB_ListaTransacoesMensais.setBounds(30, 60, 190, 23);

        JB_EfetuaPagamento.setText("Efetua Pagamento");
        JB_EfetuaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EfetuaPagamentoActionPerformed(evt);
            }
        });
        jPanel4.add(JB_EfetuaPagamento);
        JB_EfetuaPagamento.setBounds(250, 90, 190, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 130, 470, 130);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Logins do Sistema");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 10, 150, 17);

        JCB_Logins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Login1", "Login2", "Login3", "Login4" }));
        jPanel5.add(JCB_Logins);
        JCB_Logins.setBounds(10, 70, 230, 22);

        JB_VerInfoLogin.setText("Verificar Info");
        jPanel5.add(JB_VerInfoLogin);
        JB_VerInfoLogin.setBounds(20, 110, 210, 23);

        JL_NumTotalLogins.setText("Numero Total de Logins: XX");
        jPanel5.add(JL_NumTotalLogins);
        JL_NumTotalLogins.setBounds(10, 40, 220, 14);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(500, 360, 260, 160);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Alugueis e Pedidos");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(10, 10, 140, 17);

        JB_ListaPedidos.setText("Listar Pedidos");
        JB_ListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListaPedidosActionPerformed(evt);
            }
        });
        jPanel6.add(JB_ListaPedidos);
        JB_ListaPedidos.setBounds(10, 40, 170, 50);

        JCB_Alugueis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "InfoPedido1", "InfoPedido2", "InfoPedido3" }));
        jPanel6.add(JCB_Alugueis);
        JCB_Alugueis.setBounds(200, 140, 260, 22);

        JB_CancelarAluguel.setText("Cancelar");
        jPanel6.add(JB_CancelarAluguel);
        JB_CancelarAluguel.setBounds(340, 170, 100, 23);

        JB_VerInfoAluguel.setText("Ver Info");
        jPanel6.add(JB_VerInfoAluguel);
        JB_VerInfoAluguel.setBounds(210, 170, 100, 23);

        jLabel4.setText("Informacoes de Alugueis: ");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(200, 120, 260, 14);

        JB_ExcluirPedido.setText("Excluir");
        jPanel6.add(JB_ExcluirPedido);
        JB_ExcluirPedido.setBounds(380, 70, 80, 23);

        jLabel9.setText("Efetuar Pedidos:");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(200, 20, 260, 14);

        JB_VerInfoPedido.setText("Ver Info");
        jPanel6.add(JB_VerInfoPedido);
        JB_VerInfoPedido.setBounds(290, 70, 80, 23);

        JB_EfetuarPedido.setText("Efetuar");
        jPanel6.add(JB_EfetuarPedido);
        JB_EfetuarPedido.setBounds(200, 70, 80, 23);

        JCB_Pedidos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "InfoPedido1", "InfoPedido2", "InfoPedido3" }));
        jPanel6.add(JCB_Pedidos);
        JCB_Pedidos.setBounds(200, 40, 260, 22);

        JB_ListaAlugueis.setText("Lista Alugueis");
        JB_ListaAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListaAlugueisActionPerformed(evt);
            }
        });
        jPanel6.add(JB_ListaAlugueis);
        JB_ListaAlugueis.setBounds(10, 130, 170, 50);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(10, 280, 470, 240);

        JB_MenuImoveis.setText("Menu Imoveis");
        JB_MenuImoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_MenuImoveisActionPerformed(evt);
            }
        });
        getContentPane().add(JB_MenuImoveis);
        JB_MenuImoveis.setBounds(330, 70, 150, 40);

        JB_MenuClientes.setText("Menu Clientes");
        JB_MenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_MenuClientesActionPerformed(evt);
            }
        });
        getContentPane().add(JB_MenuClientes);
        JB_MenuClientes.setBounds(10, 70, 150, 40);

        JB_MenuFuncionarios.setText("Menu Funcionarios");
        JB_MenuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_MenuFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(JB_MenuFuncionarios);
        JB_MenuFuncionarios.setBounds(170, 70, 150, 40);

        JL_NumTotalPedidos.setText("Numero Total de Pedidos: XX");
        getContentPane().add(JL_NumTotalPedidos);
        JL_NumTotalPedidos.setBounds(500, 300, 170, 14);

        JL_NumTotalAlugueis.setText("Numero Total de Alugueis: XX");
        getContentPane().add(JL_NumTotalAlugueis);
        JL_NumTotalAlugueis.setBounds(500, 320, 170, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_VerFolhaDePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VerFolhaDePagamentoActionPerformed
        
        
        FolhaDePagamento folha = ControladorTransacoes.getInstance()
                .getUltimaFolhaDePagamento();
        
        if (folha == null) {
            JOptionPane.showMessageDialog(null, "Nenhum pagamento efetuado",
                    "Folha de Pagamento", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        new InterfaceListagem("Folha de Pagamento", "Ultima Folha de Pagamento",
                ControladorTransacoes.getInstance().getUltimaFolhaDePagamento()
                .getFolhaDePagamentoString()).setVisible(true);
    }//GEN-LAST:event_JB_VerFolhaDePagamentoActionPerformed

    private void JB_MenuImoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_MenuImoveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_MenuImoveisActionPerformed

    private void JB_MenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_MenuClientesActionPerformed
        new InterfaceOpClientes().setVisible(true);
    }//GEN-LAST:event_JB_MenuClientesActionPerformed

    private void JB_MenuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_MenuFuncionariosActionPerformed
        new InterfaceOpFuncionario().setVisible(true);
    }//GEN-LAST:event_JB_MenuFuncionariosActionPerformed

    private void JB_ListaTransacoesMensaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListaTransacoesMensaisActionPerformed
        new InterfaceListagem("Transacoes", "Listagem de Transacoes Mensais",
                ControladorTransacoes.getInstance().listaTransacoesMensais())
                .setVisible(true);
    }//GEN-LAST:event_JB_ListaTransacoesMensaisActionPerformed

    private void JB_ListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListaPedidosActionPerformed
        new InterfaceListagem("Pedidos", "Listagem de Pedidos", ControladorPedidos.getInstance()
                .listagemDePedido()).setVisible(true);
    }//GEN-LAST:event_JB_ListaPedidosActionPerformed

    private void JB_ListaTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListaTransacoesActionPerformed
        new InterfaceListagem("Transacoes", "Listagem de Transacoes",
                ControladorTransacoes.getInstance().listaTransacoes())
                .setVisible(true);
    }//GEN-LAST:event_JB_ListaTransacoesActionPerformed

    private void JB_EfetuaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EfetuaPagamentoActionPerformed

        try {
        FolhaDePagamento folha = ControladorTransacoes.getInstance().
                efetuaPagamentoNoMes();

        new InterfaceListagem("Folha de Pagamento", "Ultima Folha de Pagamento",
                folha.getFolhaDePagamentoString()).setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao Efetuar Pagamento:\n\n"
                    + e.getMessage(),
                    "Pagamento", JOptionPane.ERROR_MESSAGE);
        }
        atualizaInterface();
    }//GEN-LAST:event_JB_EfetuaPagamentoActionPerformed

    private void JB_ListaAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListaAlugueisActionPerformed
        new InterfaceListagem("Alugueis", "Listagem de Alugueis", ControladorAlugueis.getInstance()
                .listaAlugueis()).setVisible(true);
    }//GEN-LAST:event_JB_ListaAlugueisActionPerformed


    private void preencheCBox() {

        JCB_Alugueis.removeAllItems();
        for (String info : ControladorAlugueis.getInstance().getListaAlugueis())
            JCB_Alugueis.addItem(info);

        JCB_Logins.removeAllItems();

        for (String loginInfo : ControladorLogin.getInstance().getListaLogins())
            JCB_Logins.addItem(loginInfo);

        JCB_Pedidos.removeAllItems();
        for (String infoPedido : ControladorPedidos.getInstance().getListaPedidos())
            JCB_Pedidos.addItem(infoPedido);

        
    }

    private void atualizaInterface() {

        preencheCBox();

        if (ControladorTransacoes.getInstance().pagouNesseMes()) {
            JL_Pagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/okIcon.png")));
        } else {
            JL_Pagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/exitIcon.png")));
        }

        JL_DataUltimoPagamento.setText("Data do Ultimo Pagamento Efetuado: " +
                ControladorTransacoes.getInstance().getDataUltimoPagamento());

        JL_NumTotalAlugueis.setText("Numero Total de Alugueis: " +
                ControladorAlugueis.getInstance().numAlugueis());

        JL_NumTotalLogins.setText("Numero Total de Logins: " +
                ControladorLogin.getInstance().numLoginsCadastrados());

        JL_NumTotalPedidos.setText("Numero Total de Pedidos: " +
                ControladorPedidos.getInstance().numPedidos());

        JL_SaldoAtualCaixa.setText("Saldo Atual do Caixa: " +
                String.format("%.2f", ControladorTransacoes.getInstance().caixa()));


        preencheCBox();

        sis.salvarDados();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_CancelarAluguel;
    private javax.swing.JButton JB_EfetuaPagamento;
    private javax.swing.JButton JB_EfetuarPedido;
    private javax.swing.JButton JB_ExcluirPedido;
    private javax.swing.JButton JB_ListaAlugueis;
    private javax.swing.JButton JB_ListaPedidos;
    private javax.swing.JButton JB_ListaTransacoes;
    private javax.swing.JButton JB_ListaTransacoesMensais;
    private javax.swing.JButton JB_MenuClientes;
    private javax.swing.JButton JB_MenuFuncionarios;
    private javax.swing.JButton JB_MenuImoveis;
    private javax.swing.JButton JB_VerFolhaDePagamento;
    private javax.swing.JButton JB_VerInfoAluguel;
    private javax.swing.JButton JB_VerInfoLogin;
    private javax.swing.JButton JB_VerInfoPedido;
    private javax.swing.JComboBox JCB_Alugueis;
    private javax.swing.JComboBox JCB_Logins;
    private javax.swing.JComboBox JCB_Pedidos;
    private javax.swing.JLabel JL_DataUltimoPagamento;
    private javax.swing.JLabel JL_NumTotalAlugueis;
    private javax.swing.JLabel JL_NumTotalLogins;
    private javax.swing.JLabel JL_NumTotalPedidos;
    private javax.swing.JLabel JL_Pagamento;
    private javax.swing.JLabel JL_SaldoAtualCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
