/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 06/06/2010, 21:20:25
 */

package imobiliaria.gui;

import imobiliaria.auxiliar.TipoLogin;
import imobiliaria.controladores.ControladorLogin;
import imobiliaria.entidades.Sistema;

import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;

/**
 * GUI para tela principal
 * @author thiagofp
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupLogin = new javax.swing.ButtonGroup();
        lbLogoImob = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        txtFieldLogin = new javax.swing.JTextField();
        butCadCliente = new javax.swing.JButton();
        butSair = new javax.swing.JButton();
        butLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iMobiliaria");
        setResizable(false);

        lbLogoImob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/iMobLogo.png"))); // NOI18N

        lbLogin.setText("Login:");

        lbSenha.setText("Senha:");

        senhaField.setToolTipText("Digite sua senha aqui");

        txtFieldLogin.setToolTipText("Digite seu login aqui");

        butCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/addIcon.png"))); // NOI18N
        butCadCliente.setText("Cadastrar cliente");
        butCadCliente.setToolTipText("Ir para cadastro de cliente");
        butCadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadClienteActionPerformed(evt);
            }
        });

        butSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/exitIcon.png"))); // NOI18N
        butSair.setText("Sair");
        butSair.setToolTipText("Sai do programa");
        butSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        butLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imobiliaria/images/loginIcon.png"))); // NOI18N
        butLogar.setText("Logar");
        butLogar.setToolTipText("Clique aqui para entrar na sua conta");
        butLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(butCadCliente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLogoImob)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLogin)
                                .addGap(25, 25, 25)
                                .addComponent(txtFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSenha)
                                .addGap(18, 18, 18)
                                .addComponent(senhaField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(butLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbLogoImob)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(txtFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butLogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCadCliente)
                    .addComponent(butSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadClienteActionPerformed
//        new CadastraCliente().setVisible(true);
//        dispose();

    }//GEN-LAST:event_butCadClienteActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butSairActionPerformed

    private void butLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogarActionPerformed
        String login = txtFieldLogin.getText();
        String senha = senhaField.getText();

        if(senha.replace(" ", "").equals("") ||
                login.replace(" ", "").equals("")){
            JOptionPane.showMessageDialog(null, "Campos de login ou senha não" +
                    " podem estar vazio\n\n Por favor, digite novamente.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

        boolean loga = false;

        if (ControladorLogin.getInstance().verificaLogin(login)) {
            if (ControladorLogin.getInstance().
                    getLogin(login).getSenha().equals(senha)) {
                loga = true;
            }
        }


        if (loga) {
           // muda de tela, faz algo pra logar, seila! rs! =P
        }

//        if (rdbAdmin.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.ADMINISTRADOR)){
//                new AdministradorGUI().setVisible(true);
//                dispose();
//        }
//
//
//        } else if (rdbCliente.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.CLIENTE)){
//                new ClienteGUI().setVisible(true);
//                dispose();
//            }
//        } else if (rdbFunc.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.FUNCIONARIO)){
//                new FuncionarioGUI().setVisible(true);
//                dispose();
//            }
//
//
//        }


        
    }//GEN-LAST:event_butLogarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadCliente;
    private javax.swing.ButtonGroup butGroupLogin;
    private javax.swing.JButton butLogar;
    private javax.swing.JButton butSair;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogoImob;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JTextField txtFieldLogin;
    // End of variables declaration//GEN-END:variables
    // Atributos
    private Sistema sistema;
 // Fim de declaracao de atributos
}
