/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 06/06/2010, 21:20:25
 */

package imobiliaria.gui;

import imobiliaria.auxiliar.TipoLogin;
import imobiliaria.entidades.Sistema;

import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;

/**
 * GUI para tela principal
 * @author thiagofp
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
  	  setUndecorated(true);  
  	  getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
    	
    	try{
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
			
		}
		catch(Exception e){
			System.out.println("Nimbus isn't available");
		}
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupLogin = new javax.swing.ButtonGroup();
        lbLogoImob = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        txtFieldLogin = new javax.swing.JTextField();
        butCadCliente = new javax.swing.JButton();
        butSair = new javax.swing.JButton();
        butLogar = new javax.swing.JButton();
        rdbCliente = new javax.swing.JRadioButton();
        rdbFunc = new javax.swing.JRadioButton();
        rdbAdmin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iMobiliaria");
        setResizable(false);

        lbLogoImob.setIcon(new javax.swing.ImageIcon("/home/thiagofp/workspace/iMobiliaria/img/iMobLogo.png")); // NOI18N

        lbLogin.setText("Login:");

        lbSenha.setText("Senha:");

        senhaField.setToolTipText("Digite sua senha aqui");

        txtFieldLogin.setToolTipText("Digite seu login aqui");

        butCadCliente.setText("Cadastrar cliente");
        butCadCliente.setToolTipText("Ir para cadastro de cliente");
        butCadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadClienteActionPerformed(evt);
            }
        });

        butSair.setText("Sair");
        butSair.setToolTipText("Sai do programa");
        butSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSairActionPerformed(evt);
            }
        });

        butLogar.setText("Logar");
        butLogar.setToolTipText("Clique aqui para entrar na sua conta");
        butLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogarActionPerformed(evt);
            }
        });

        butGroupLogin.add(rdbCliente);
        rdbCliente.setSelected(true);
        rdbCliente.setText("Cliente");
        rdbCliente.setToolTipText("Escolha uma das opções de login");

        butGroupLogin.add(rdbFunc);
        rdbFunc.setText("Funcionário");
        rdbFunc.setToolTipText("Escolha uma das opções de login");

        butGroupLogin.add(rdbAdmin);
        rdbAdmin.setText("Administrador");
        rdbAdmin.setToolTipText("Escolha uma das opções de login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(lbLogoImob)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(butSair, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butCadCliente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbLogin)
                        .addGap(25, 25, 25)
                        .addComponent(txtFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSenha)
                        .addGap(18, 18, 18)
                        .addComponent(senhaField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addGap(233, 233, 233))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbCliente)
                        .addGap(18, 18, 18)
                        .addComponent(rdbFunc)))
                .addGap(18, 18, 18)
                .addComponent(rdbAdmin)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogoImob)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogin)
                    .addComponent(txtFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbCliente)
                    .addComponent(rdbFunc)
                    .addComponent(rdbAdmin))
                .addGap(18, 18, 18)
                .addComponent(butLogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCadCliente)
                    .addComponent(butSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadClienteActionPerformed
//        new CadastraCliente().setVisible(true);
//        dispose();

    }//GEN-LAST:event_butCadClienteActionPerformed

    private void butSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butSairActionPerformed

    private void butLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogarActionPerformed
        String login = txtFieldLogin.getText();
        String senha = senhaField.getText();

        if(senha.replace(" ", "").equals("") ||
                login.replace(" ", "").equals("")){
            JOptionPane.showMessageDialog(null, "Campos de login ou senha não" +
                    " podem estar vazio\n\n Por favor, digite novamente.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }

//        if (rdbAdmin.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.ADMINISTRADOR)){
//                new AdministradorGUI().setVisible(true);
//                dispose();
//        }
//
//
//        } else if (rdbCliente.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.CLIENTE)){
//                new ClienteGUI().setVisible(true);
//                dispose();
//            }
//        } else if (rdbFunc.isSelected()){
//            if(sistema.login(login, senha, TipoLogin.FUNCIONARIO)){
//                new FuncionarioGUI().setVisible(true);
//                dispose();
//            }
//
//
//        }


        
    }//GEN-LAST:event_butLogarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadCliente;
    private javax.swing.ButtonGroup butGroupLogin;
    private javax.swing.JButton butLogar;
    private javax.swing.JButton butSair;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLogoImob;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JRadioButton rdbAdmin;
    private javax.swing.JRadioButton rdbCliente;
    private javax.swing.JRadioButton rdbFunc;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JTextField txtFieldLogin;
    // End of variables declaration//GEN-END:variables
    // Atributos
    private Sistema sistema;
 // Fim de declaracao de atributos
}
