/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfaceListagem.java
 *
 * Created on 05/07/2010, 15:24:44
 */

package imobiliaria.gui;

/**
 *
 * @author Convidado
 */
public class InterfaceListagem extends javax.swing.JFrame {

    /** Creates new form InterfaceListagem */
    public InterfaceListagem(String titulo, String listagemDe, String lista) {
        initComponents();
        setLocationRelativeTo(null);

        JL_ListagemDe.setText(listagemDe);
        JTA_Lista.setText(lista);
        setTitle(titulo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_Lista = new javax.swing.JTextArea();
        JL_ListagemDe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem");
        setMinimumSize(new java.awt.Dimension(395, 500));
        setName("Listagem"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        JTA_Lista.setColumns(20);
        JTA_Lista.setEditable(false);
        JTA_Lista.setRows(5);
        jScrollPane1.setViewportView(JTA_Lista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 370, 420);

        JL_ListagemDe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JL_ListagemDe.setText("Listagem de ");
        getContentPane().add(JL_ListagemDe);
        JL_ListagemDe.setBounds(10, 10, 370, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceListagem("Titulo", "Listagem de Teste", "LISTANDO NADA").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_ListagemDe;
    private javax.swing.JTextArea JTA_Lista;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
